# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fb0e3e7040b86f2324cbd10c26bcee37044607e263bac38ea8ca028ef8e9efc85d669587b541fadf0b236dc88a26eddbff86816423c33033e4759eb51f99b0e

test:
  secret_key_base: 3cf7a5efc4f49a9343db1caf18dcfd76be584bf008d853075d99a3672eb806e3736b7adeae256ea41d196ab7008da70d9a492cb42f6fb4faafcbd0304882937b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
